wandb_version: 1

model_name:
  desc: null
  value: tUNet_UCSF_crop
type_ae:
  desc: null
  value: unet
num_blocks:
  desc: null
  value: 5
features:
  desc: null
  value: 8
model_path:
  desc: null
  value: outputs/UNet_crop/tUNet_UCSF_crop
dataset:
  desc: null
  value: UCSF
data_path:
  desc: null
  value: data/MR
modalities:
  desc: null
  value:
  - T1c_crop
  - FLAIR_crop
min_dims:
  desc: null
  value:
  - 75
  - 71
  - 62
batch_size:
  desc: null
  value: 1
whole_brain:
  desc: null
  value: false
num_epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
num_workers:
  desc: null
  value: 6
quick:
  desc: null
  value: false
beta:
  desc: null
  value: '1'
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682983279.810958
    t:
      1:
      - 1
      - 41
      - 48
      - 51
      - 55
      2:
      - 1
      - 41
      - 48
      - 51
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      4: 3.9.0
      5: 0.15.0
      8:
      - 5
