wandb_version: 1

model_name:
  desc: null
  value: VAE3D_UKB
type_ae:
  desc: null
  value: VAE3D
num_blocks:
  desc: null
  value: 6
features:
  desc: null
  value: 4
model_path:
  desc: null
  value: outputs/VAE/VAE3D_UKB
dataset:
  desc: null
  value: UKBIOBANK
data_path:
  desc: null
  value: data/MR
modalities:
  desc: null
  value:
  - t1
  - FLAIR
  - black
min_dims:
  desc: null
  value:
  - 156
  - 185
  - 149
batch_size:
  desc: null
  value: 3
whole_brain:
  desc: null
  value: true
num_epochs:
  desc: null
  value: 300
learning_rate:
  desc: null
  value: 0.0001
num_workers:
  desc: null
  value: 6
quick:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682468803.627427
    t:
      1:
      - 1
      - 41
      - 48
      - 51
      - 55
      2:
      - 1
      - 41
      - 48
      - 51
      - 55
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.9.0
      5: 0.15.0
      8:
      - 5
