# src/config/config.yaml
# Resource paths
paths:
  scripts:
    preprocessing: "scripts/preprocessing"
  templates: "data/templates"
  models: "data/models"

# Preprocessing options
preprocessing:
  # Parameters for preprocessing scripts
  parameters:
    brain_extraction:
      threshold: 0.5
    bias_correction:
      iterations: 4
  
  # If true, skips the brain extraction step
  skip_brain_extraction: false
  
  # If true, keeps preprocessed files in the output folder
  keep_preprocessed: false

# Model options
model:
  weights_file: "U-AE.pt"
  input_size: [256, 256, 256]

# Output options
output:
  # Enable/disable log files
  enable_logs: true

# Pipeline control options
pipeline:
  # If true, only performs feature extraction (skips conversion and preprocessing)
  features_only: false