# src/config/config.yaml
paths:
  scripts:
    preprocessing: "scripts/preprocessing"
  templates: "data/templates"
  models: "data/models"

preprocessing:
  parameters:
    brain_extraction:
      threshold: 0.5
    bias_correction:
      iterations: 4
  # Nouvelle option pour sauter l'extraction du cerveau si déjà fait
  skip_brain_extraction: false
  # Nouvelle option pour conserver les fichiers préprocessés
  keep_preprocessed: false

# Support pour les fichiers NIfTI
input:
  support_nifti: true

# Options de sortie
output:
  simplified_structure: true

model:
  weights_file: "best_model.pt"
  input_size: [256, 256, 256]