wandb_version: 1

model_name:
  desc: null
  value: VAE3D_UCSF_b10
type_ae:
  desc: null
  value: VAE3D
num_blocks:
  desc: null
  value: 6
features:
  desc: null
  value: 4
beta:
  desc: null
  value: '0.1'
latent_dim:
  desc: null
  value: 2048
model_path:
  desc: null
  value: outputs/VAE3D/VAE3D_UCSF_b10
dataset:
  desc: null
  value: UCSF
data_path:
  desc: null
  value: data/MR
modalities:
  desc: null
  value:
  - T1c
  - FLAIR
  - SegmBinary
min_dims:
  desc: null
  value:
  - 154
  - 180
  - 150
batch_size:
  desc: null
  value: 8
whole_brain:
  desc: null
  value: true
num_epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0001
num_workers:
  desc: null
  value: 6
quick:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683257451.837765
    t:
      1:
      - 1
      - 41
      - 48
      - 51
      - 55
      2:
      - 1
      - 41
      - 48
      - 51
      - 55
      3:
      - 14
      - 16
      - 23
      4: 3.9.0
      5: 0.15.0
      8:
      - 5
