wandb_version: 1

model_name:
  desc: null
  value: tAE_UCSF_augm
type_ae:
  desc: null
  value: oldae
num_blocks:
  desc: null
  value: 5
features:
  desc: null
  value: 8
model_path:
  desc: null
  value: outputs/AE_crop/tAE_UCSF_augm
dataset:
  desc: null
  value: UCSF_crop
data_path:
  desc: null
  value: data/MR
modalities:
  desc: null
  value:
  - T1c_crop
  - FLAIR_crop
min_dims:
  desc: null
  value:
  - 75
  - 94
  - 62
batch_size:
  desc: null
  value: 15
whole_brain:
  desc: null
  value: false
num_epochs:
  desc: null
  value: 2000
learning_rate:
  desc: null
  value: 0.0001
num_workers:
  desc: null
  value: 2
quick:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682630762.473739
    t:
      1:
      - 1
      - 41
      - 48
      - 51
      - 55
      3:
      - 14
      - 16
      - 23
      4: 3.9.0
      5: 0.15.0
      8:
      - 5
